addSbtPlugin("org.scala-sbt"  % "sbt-houserules"  % "0.3.9")
addSbtPlugin("com.lucidchart" % "sbt-scalafmt"    % "1.15")
addSbtPlugin("org.scala-sbt"  % "sbt-contraband"  % "0.4.1")
addSbtPlugin("com.eed3si9n"   % "sbt-buildinfo"   % "0.7.0")
addSbtPlugin("com.lightbend"  % "sbt-whitesource" % "0.1.9")
addSbtPlugin("de.heikoseeberger" % "sbt-header" % "5.1.0")
