name: CI
on:
  pull_request:
  push:

env:
  SCALA212: 2.12.*
  SCALA213: 2.13.*
  SCALA3: 3.*

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            java: 8
            distribution: zulu
            jobtype: 1
          - os: ubuntu-latest
            java: 11
            distribution: temurin
            jobtype: 2
          - os: ubuntu-latest
            java: 17
            distribution: temurin
            jobtype: 2
          - os: ubuntu-latest
            java: 21
            distribution: temurin
            jobtype: 2
          - os: macos-latest
            java: 11
            distribution: temurin
            jobtype: 2
          - os: windows-2025
            java: 8
            distribution: zulu
            jobtype: 3
    runs-on: ${{ matrix.os }}
    env:
      JAVA_OPTS: -Dsbt.io.virtual=false -Dfile.encoding=UTF-8
      JVM_OPTS: -Dsbt.io.virtual=false -Dfile.encoding=UTF-8
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    - name: Setup JDK
      uses: actions/setup-java@v5
      with:
        distribution: "${{ matrix.distribution }}"
        java-version: "${{ matrix.java }}"
        cache: sbt
    - name: Setup sbt
      uses: sbt/setup-sbt@v1
    - name: Build and test (1)
      if: ${{ matrix.jobtype == 1 }}
      shell: bash
      run: |
        sbt -v -Dfile.encoding=UTF8 -Dsbt.test.fork=true ++$SCALA212 mimaReportBinaryIssues scalafmtCheckAll headerCheck Test/headerCheck test doc
        sbt -v -Dfile.encoding=UTF8 -Dsbt.test.fork=false ++$SCALA213 test ++$SCALA3 test
    - name: Build and test (2)
      if: ${{ matrix.jobtype == 2 }}
      shell: bash
      run: |
        sbt -v -Dfile.encoding=UTF8 -Dsbt.test.fork=true ++$SCALA212 mimaReportBinaryIssues test
        sbt -v --client ++$SCALA213
        sbt -v --client test
        sbt -v --client ++$SCALA3
        sbt -v --client test
    - name: Build and test (3)
      if: ${{ matrix.jobtype == 3 }}
      shell: bash
      run: |
        sbt -v -Dfile.encoding=UTF8 -Dsbt.test.fork=true ++$SCALA212 test
        sbt -v --client ++$SCALA213
        sbt -v --client test
        sbt -v --client ++$SCALA3
        sbt -v --client test
